name: .NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish-linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish for Linux
      run: dotnet publish -c Release -r linux-x64 --self-contained true -o ./publish/linux

    - name: Compress Linux Artifact
      run: |
        mkdir -p ./compressed
        zip -r ./compressed/linux-artifact.zip ./publish/linux

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: ./compressed/linux-artifact.zip

  publish-windows:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish for Windows
      run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish/windows

    - name: Compress Windows Artifact
      run: |
        mkdir compressed
        Compress-Archive -Path ./publish/windows/* -DestinationPath ./compressed/windows-artifact.zip

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: ./compressed/windows-artifact.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [publish-linux, publish-windows]
    steps:
    - uses: actions/checkout@v4

    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-artifact
        path: ./compressed

    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-artifact
        path: ./compressed

    - name: Bump version and push tag
      id: bump
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Linux Artifact to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        files: ./compressed/linux-artifact.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows Artifact to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        files: ./compressed/windows-artifact.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
